export default {
    DELETE_EVENT_FROM_CELL: "DELETE_EVENT_FROM_CELL",
    REPLACE_EVENT: "REPLACE_EVENT",
    SUBCELL_HOVERED: "SUBCELL_HOVERED",
    SET_START_NUM: "SET_START_NUM",
    SET_SUBCELL_DIRECTION: "SET_SUBCELL_DIRECTION",
    SET_END_NUM: "SET_END_NUM",
    REMOVE_COLLISIONS: "REMOVE_COLLISIONS",
    CLEAR_COLLISIONS: "CLEAR_COLLISIONS",
    SWITCH_DRAG: "SWITCH_DRAG",
    SET_END_TIME: "SET_END_TIME",
    RESIZE_EVENT: "RESIZE_EVENT"
}